[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

# Redirect old blog post URLs
[[redirects]]
  from = "blog/*"
  to = "/:splat"

# Netlify settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true